export enum NotificationType {
    'MESSAGE' = 'MESSAGE',
    'FRIEND_REQUEST' = 'FRIEND_REQUEST',
    'FRIEND_REQUEST_ACCEPT' = 'FRIEND_REQUEST_ACCEPT',
    'GROUP_INVITATION' = 'GROUP_INVITATION',
    'GROUP_MEMBER_ADD' = 'GROUP_MEMBER_ADD'
}
